- name: "Get User home directory"
  ansible.builtin.command: getent passwd {{ ansible_user }}
  register: user_info
- ansible.builtin.set_fact:
    user_home: "{{user_info.stdout.split(':')[5]}}"

- name: "Install uv"
  ansible.builtin.get_url:
    url: https://astral.sh/uv/install.sh
    dest: /tmp/uv_install.sh
    mode: "0755"
- ansible.builtin.command: sh /tmp/uv_install.sh
  become: yes
  become_user: "{{ ansible_user }}"

- name: "Add path"
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: "export PATH=$HOME/.local/bin:$PATH"
    insertafter: EOF
    state: present
