- name: "Install virtualbox"
  ansible.builtin.get_url:
    url: https://download.virtualbox.org/virtualbox/7.1.8/virtualbox-7.1_7.1.8-168469~Ubuntu~{{ ansible_lsb.codename }}_amd64.deb
    dest: /tmp/virtualbox.deb
- ansible.builtin.apt:
    deb: /tmp/virtualbox.deb
    update_cache: yes
- ansible.builtin.apt:
    update_cache: yes
    name:
      - build-essential
      - dkms
      - linux-headers-{{ ansible_kernel }}
- ansible.builtin.command: /sbin/vboxconfig
