- name: "Set dpkg architecture"
  ansible.builtin.set_fact:
    dpkg_arch: >-
      {{ "amd64" if ansible_architecture == "x86_64" else "arm64" if ansible_architecture == "aarch64" else ansible_architecture }}

- name: "Add Docker's official GPG key"
  ansible.builtin.apt:
    update_cache: yes
    name:
      - ca-certificates
      - curl
- ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755
- ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0555

- name: "Add the repository to Apt sources"
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ dpkg_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: "Install latest version"
  ansible.builtin.apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: "Add user to docker group"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: "Restart Docker service"
  ansible.builtin.service:
    name: docker
    state: restarted
