- name: "Install xrdp"
  ansible.builtin.apt:
    update_cache: yes
    name:
      - xrdp
      - xserver-xorg-video-dummy

- name: "set dummy display"
  ansible.builtin.copy:
    dest: /usr/share/X11/xorg.conf.d/xorg.conf
    content: |
      Section "Device"
      Identifier "Configured Video Device"
      Driver "dummy"
      EndSection

      Section "Monitor"
      Identifier "Configured Monitor"
      HorizSync 31.5-48.5
      VertRefresh 50-70
      EndSection

      Section "Screen"
      Identifier "Default Screen"
      Monitor "Configured Monitor"
      Device "Configured Video Device"
      DefaultDepth 24
      SubSection "Display"
      Depth 24
      Modes "1024x800"
      EndSubSection
      EndSection

- name: "Restart xrdp service"
  ansible.builtin.service:
    name: xrdp
    state: restarted
